name: 'Speech to Text OpenAI Whisper'
description: 'High-performance inference of OpenAI Whisper automatic speech recognition (ASR) model'
author: 'Bo-Yi Wu'
inputs:
  model:
    description: 'public whisper model, standard or quantized (e.g. large-v3-turbo, large-v3-turbo-q5_0, large-v3-q5_0, large-v2-q5_0, medium-q5_0, small-q5_1, base-q5_1, tiny-q5_1)'
    default: 'large-v3-turbo-q5_0'
  audio_path:
    description: 'Audio Path.'
  output_folder:
    description: 'output folder.'
  output_format:
    description: 'output format, support txt, srt, csv.'
    default: 'txt'
  output_filename:
    description: 'output filename.'
  debug:
    description: 'enable debug mode.'
  print_progress:
    description: 'print progress.'
    default: 'true'
  print_segment:
    description: 'print segment.'
  youtube_url:
    description: 'youtube url(s) (supports single or multiple URLs separated by newlines, commas, or spaces)'
  youtube_urls:
    description: 'alias for youtube_url'
  translate:
    description: 'translate from source language to english'
  cut_silences:
    description: 'cut silences'
  prompt:
    description: 'initial prompt'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'
